categories_list=[
    "fitness",
    "health",
    "nutrition",
    "technology",
    "programming",
    "science",
    "mathematics",
    "education",
    "business",
    "finance",
    "economics",
    "marketing",
    "entrepreneurship",
    "leadership",
    "self-improvement",
    "psychology",
    "philosophy",
    "history",
    "politics",
    "law",
    "environment",
    "sustainability",
    "travel",
    "culture",
    "languages",
    "literature",
    "art",
    "music",
    "film",
    "gaming",
    "sports",
    "outdoors",
    "fashion",
    "design",
    "photography",
    "cooking",
    "food",
    "relationships",
    "parenting",
    "spirituality",
    "religion",
    "meditation",
    "mindfulness",
    "productivity",
    "career",
    "real estate",
    "cryptocurrency",
    "machine learning",
    "artificial intelligence",
    "data science",
    "cybersecurity",
    "web development",
    "mobile development",
    "hardware",
    "networking",
    "robotics",
    "astronomy",
    "biology",
    "chemistry",
    "physics",
    "engineering",
    "mechanics",
    "automotive",
    "DIY",
    "gardening",
    "pets",
    "luxury",
    "lifestyle",
    "news",
    "current events",
    "memes",
    "comedy",
    "social media",
    "photography",
    "writing",
    "poetry",
    "journalism",
    "political science"
]